chain:
    bech32_prefix: cosmos
    modules: []
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://host.docker.internal:26657
            max_connections: 20
        grpc:
            address: host.docker.internal:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 5s
database:
    name: stratos_db
    host: postgres
    port: 5432
    user: stratos
    password: stratos
    schema: public
    max_open_connections: 1
    max_idle_connections: 1
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
actions:
    port: 3000